apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: {{ .Release.Name }}-secrets
    labels:
        app: {{ template "app.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
data:
    HERE_MAPS_API_ID: {{ required "app.config.autocomplete.apiId" .Values.app.config.autocomplete.apiId | b64enc }}
    HERE_MAPS_APP_CODE: {{ required "app.config.autocomplete.appCode" .Values.app.config.autocomplete.appCode | b64enc }}
    DARKSKY_API_KEY: {{ required "app.config.weather.apiKey" .Values.app.config.weather.apiKey | b64enc }}
